services:
  my-finance-tracker:
    container_name: my-finance-tracker
    ports:
      - "${PORT:-4242}:3000"
    volumes:
      - ./data:/app/data
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION:-true}
      - NODE_ENV=${NODE_ENV:-production}
    restart: unless-stopped